/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nvxmfxqccbdgybqnfwlx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52eG1meHFjY2JkZ3licW5md2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MTc2MzIsImV4cCI6MjA3ODk5MzYzMn0.VYXXO39syuCxaUrie-Ql8FVgY16d1B-KZ3Y-1ke5RnQ"